/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiAppVersion from "@palmabit/strapi-app-version/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import upload from "@strapi/plugin-upload/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import publisher from "strapi-plugin-publisher/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-app-version": strapiAppVersion,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    upload: upload,
    "users-permissions": usersPermissions,
    publisher: publisher,
  },
});
